project:
  type: website

website:
  title: "Flashy Blog name"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ReanFernandes
      
  site-url: ReanFernandes.github.io
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
execute:
  freeze: auto